name: Continuous integration
on: [push]
jobs:
  linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd src && make
      - run: mkdir artifacts && cp src/*.h src/*.so artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-artifacts
          path: artifacts
