name: Continuous integration
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd src
          make
          zip -r non-layered-tidy-trees-ubuntu.zip *.h *.so
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create r${{github.run_number}} src/non-layered-tidy-trees-ubuntu.zip

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            curl
            git
            zip
            mingw-w64-ucrt-x86_64-toolchain
      - uses: actions/checkout@v4
      - name: Build
        shell: msys2 {0}
        run: |
          cd src
          mingw32-make mingw
          zip -r non-layered-tidy-trees-win-ucrt64.zip *.h *.dll
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: gh release upload r${{github.run_number}} src/non-layered-tidy-trees-win-ucrt64.zip