name: Continuous integration
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd src && make
      - run: |
          mkdir artifacts && cp src/*.h src/*.so artifacts/
          zip -r artifacts.zip artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu
          path: artifacts
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload artifacts.zip

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            curl
            git
            zip
            mingw-w64-ucrt-x86_64-toolchain
      - uses: actions/checkout@v4
      - shell: msys2 {0}
        run: |
          cd src
          mingw32-make mingw
      - shell: msys2 {0}
        run: |
          mkdir artifacts && cp src/*.h src/*.dll artifacts/
          zip -r artifacts.zip artifacts
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: gh release upload ${{ github.run_id }} artifacts.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: artifacts
        