name: Continuous integration
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd src && make
      - run: |
          cd src
          make
          cd ..
          mkdir artifacts && mv src/*.h src/*.so artifacts/
        # zip -r ubuntu-latest.zip src/*.h src/*.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest
          path: artifacts
      # - name: Upload release assets
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh release create r${{github.run_number}} ubuntu-latest.zip

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            curl
            git
            zip
            mingw-w64-ucrt-x86_64-toolchain
      - uses: actions/checkout@v4
      - shell: msys2 {0}
        run: |
          cd src
          mingw32-make mingw
          cd ..
          mkdir artifacts && mv src/*.h src/*.dll artifacts/
        # zip -r win-ucrt64.zip artifacts
      # - name: Upload release assets
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   shell: cmd
      #   run: gh release upload r${{github.run_number}} win-ucrt64.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-ucrt
          path: artifacts
        